import {
  AlertCircle,
  ArrowDownRight,
  ArrowLeft,
  ArrowUpDown,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Building2,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Copy,
  CreditCard,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gift,
  Globe,
  History,
  Inbox,
  Link2,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  PanelLeft,
  PanelLeftClose,
  PanelRight,
  Paperclip,
  Phone,
  Plane,
  Plus,
  Puzzle,
  Radio,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  Smile,
  Sparkles,
  Sun,
  Tag,
  Trash2,
  TrendingUp,
  Unplug,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Workflow,
  X,
  XCircle,
  Zap,
  type LucideProps,
} from "lucide-react"

export type Icon = React.ComponentType<LucideProps>

export const Icons = {
  alertCircle: AlertCircle,
  arrowDownRight: ArrowDownRight,
  arrowLeft: ArrowLeft,
  arrowUpDown: ArrowUpDown,
  arrowUpRight: ArrowUpRight,
  barChart3: BarChart3,
  bell: Bell,
  bookOpen: BookOpen,
  bot: Bot,
  building2: Building2,
  calendar: Calendar,
  check: Check,
  checkCheck: CheckCheck,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  checkSquare: CheckSquare,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  download: Download,
  edit: Edit3,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  filter: Filter,
  gift: Gift,
  globe: Globe,
  history: History,
  inbox: Inbox,
  link: Link2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  messagesSquare: MessagesSquare,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
  panelRight: PanelRight,
  paperclip: Paperclip,
  phone: Phone,
  plane: Plane,
  plus: Plus,
  puzzle: Puzzle,
  radio: Radio,
  refreshCw: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  smile: Smile,
  sparkles: Sparkles,
  spinner: Loader2,
  sun: Sun,
  tag: Tag,
  trash: Trash2,
  trendingUp: TrendingUp,
  unplug: Unplug,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  volume2: Volume2,
  workflow: Workflow,
  x: X,
  xCircle: XCircle,
  zap: Zap,
}
